export { default as Footer } from './footer/Footer'
export { default as Contact } from './contact/Contact'
export { default as Clients } from './clients/Clients'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as Team } from './team/Team'
