export { default as Footer } from './footer/Footer'
export { default as Contact } from './contact/Contact'
export { default as Clients } from './clients/Clients'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as Team } from './team/Team'
export { default as Services } from './services/Services'
export { default as Partners } from './partners/Partners'
export { default as Slide } from './slide/Slide'
